//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonSatisProjesi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database3Entities : DbContext
    {
        public Database3Entities()
            : base("name=Database3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBBELLEK> TBBELLEK { get; set; }
        public virtual DbSet<TBKAT> TBKAT { get; set; }
        public virtual DbSet<TBMARKA> TBMARKA { get; set; }
        public virtual DbSet<TBMODEL> TBMODEL { get; set; }
        public virtual DbSet<TBMUSTERI> TBMUSTERI { get; set; }
        public virtual DbSet<TBRAM> TBRAM { get; set; }
        public virtual DbSet<TBSALISAN> TBSALISAN { get; set; }
        public virtual DbSet<TBTELEFON> TBTELEFON { get; set; }
    }
}
