//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonSatisProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMUSTERI
    {
        public int Id { get; set; }
        public string ADISOYADI { get; set; }
        public string NUMARA { get; set; }
        public string KULADI { get; set; }
        public string SIFRE { get; set; }
        public Nullable<System.DateTime> DOGUM { get; set; }
        public string EMAIL { get; set; }
        public string KIMLIK { get; set; }
    }
}
