//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonSatisProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBTELEFON
    {
        public int Id { get; set; }
        public string BELLEK { get; set; }
        public string ISLEMCI { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string GARANTI { get; set; }
        public string STOK { get; set; }
        public string RENK { get; set; }
        public byte[] RESIM { get; set; }
        public string KAT { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public string RAM { get; set; }
        public int MARKA_ID { get; set; }
        public int KAT_ID { get; set; }
        public int BELLEK_ID { get; set; }
        public int MODEL_ID { get; set; }
        public int TBMARKA_ID { get; set; }
    }
}
